/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.NhanVienDAO;
import Models.NhanVien;
import Models.listAccoutRemembers;
import NewInterface.MainInterface;
import helper.Auth;
import helper.DataValidator;
import helper.MsgBox;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 *
 * @author FPT
 */
public class dangnhap extends javax.swing.JFrame {

    /**
     * Creates new form dn
     */
    MainInterface<NhanVien> qlNV;
    listAccoutRemembers listAR;
    private String rememberID = "";
    private String remembersPass = "";
    private String path = "LoginRemembers.txt";

    public dangnhap() {
        initComponents();
        setLocationRelativeTo(null);
//        this.setIconImage(XImage.getAppIcon());
        qlNV = new NhanVienDAO();
        this.listAR = new listAccoutRemembers();
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(path));
            this.listAR = (listAccoutRemembers) ois.readObject();
            this.rememberID = listAR.getId();
            this.remembersPass = listAR.getPass();
            ois.close();
        } catch (Exception e) {
            e.printStackTrace();
//            MsgBox.alert(this, "Chưa có ID nào được lưu!");
        }

        this.txtUserName.setText(rememberID);
        this.txtPassWord.setText(remembersPass);
        this.chkNhoMK.setSelected(rememberID.equals("") ? false : true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        chkNhoMK = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 27, 54));

        jLabel3.setForeground(new java.awt.Color(122, 160, 173));
        jLabel3.setText("Tên đăng nhập : ");

        jLabel5.setForeground(new java.awt.Color(122, 160, 173));
        jLabel5.setText("Mật khẩu : ");

        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });

        txtPassWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassWordMousePressed(evt);
            }
        });
        txtPassWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassWordKeyPressed(evt);
            }
        });

        chkNhoMK.setBackground(new java.awt.Color(27, 27, 54));
        chkNhoMK.setForeground(new java.awt.Color(122, 160, 173));
        chkNhoMK.setText("Nhớ mật khẩu ?");

        jLabel7.setBackground(new java.awt.Color(95, 175, 32));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(122, 160, 173));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Đăng nhập");

        jLabel1.setForeground(new java.awt.Color(122, 160, 173));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quên mật khẩu ?");

        btnLogin.setBackground(new java.awt.Color(165, 30, 76));
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(122, 160, 173));
        btnLogin.setText("ĐĂNG NHẬP");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserName)
                    .addComponent(txtPassWord)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNhoMK)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkNhoMK)
                .addGap(8, 8, 8)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        this.enter(evt);
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void txtPassWordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassWordMousePressed

    }//GEN-LAST:event_txtPassWordMousePressed

    private void txtPassWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassWordKeyPressed
        this.enter(evt);
    }//GEN-LAST:event_txtPassWordKeyPressed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkNhoMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
private void login() {

        String tenDN = txtUserName.getText();
        String matKhau = new String(txtPassWord.getPassword());
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtUserName, sb, "Không để trống ID!");
        DataValidator.validateEmpty(txtPassWord, sb, "Không để trống pass!");
        if (sb.length() > 0) {
            MsgBox.showErrorDialog(this, sb.toString(), "Error !");
            return;
        } else {
        }
        try {
            NhanVien nv = null;
            nv = qlNV.selectById(tenDN);
            if (nv == null) {
                MsgBox.showErrorDialog(this, "Sai tên Đăng Nhập", "Error !");
                txtUserName.setBackground(Color.YELLOW);
                return;
            } else if (!matKhau.equals(nv.getMatKhau())) {
                MsgBox.showErrorDialog(this, "Sai mật khẩu", "Error !");
                txtPassWord.setBackground(Color.YELLOW);
                return;
            } else {
                Auth.user = nv;
                this.rememberLogin();
                MsgBox.alert(this, "Xin chào, " + (Auth.user.getChucVu() ? "Admin" : "Nhân Viên") + ": " + (Auth.user.getTenNV()));
                this.setVisible(false);
                new quanly().setVisible(true);
            }
        } catch (Exception ex) {
            MsgBox.showErrorDialog(this, "Lỗi Đăng Nhập!", "Error !");
            ex.printStackTrace();
        }
    }

    private void rememberLogin() {
        if (this.chkNhoMK.isSelected()) {
            this.rememberID = txtUserName.getText();
            this.remembersPass = String.valueOf(txtPassWord.getPassword());
        } else {
            this.rememberID = "";
            this.remembersPass = "";
        }
        listAR = new listAccoutRemembers(rememberID, remembersPass);
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(path));
            oos.writeObject(listAR);
        } catch (IOException e) {
            e.printStackTrace();
            MsgBox.showErrorDialog(this, "Ghi nhớ mật khẩu thất bại!", "Error !");

        }
    }

    private void enter(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.btnLogin.doClick();
        }
    }

    private void exit() {
        System.exit(0);
    }
}
